language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gengetopt help2man $EXTRA
env:
  - EXTRA="libjson0-dev libudev-dev libusb-1.0-0-dev"
script:
  - ./build-aux/travis
